apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base]
secretGenerator:
  - name: service-notify-secrets
    namespace: geovannycode
    envs: [.env]
configMapGenerator:
  - name: service-notify-config
    namespace: geovannycode
    behavior: merge
    literals:
      - TRACING_SAMPLING=1.0
      - OTEL_TRACES_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
patches:
  - target:
      kind: Deployment
      name: service-notify
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Service
      name: service-notify
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30082
